### ISSUE TITLE
Unable to ssh to the machine

### ISSUE THREAD

**Issue by houranii** [appsembler/openedx-azure-scalable#5]
After edX installs it blocks the password ssh access, without having the public ssh-key, I am unable to connect to the machine.

**Comment by chenriksson** [comment]
This is default Open edX behavior. You can prevent it by setting 'COMMON_SSH_PASSWORD_AUTH: "yes"' in extra-vars.yml (configure-openedx.sh), or ssh-copy-id your public key to the first app VM (port 2222) while Open edX is installing.

**Comment by houranii** [comment]
Thanks chenriksson, I figured it out some time ago but forgot to update it here.

**Comment by chenriksson** [comment]
NP, just sharing here in case anyone else needs it.

Also see [VMAccess Extension](https://azure.microsoft.com/en-us/blog/using-vmaccess-extension-to-reset-login-credentials-for-linux-vm/) to regain access.
